In [2]:
import numpy as np


---
# VIDEO: A zoo of matrices
---


In [6]:

# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(R)

# identity
I = np.eye(3)
print(I)

# zeros
Z = np.zeros((4,4))
print(Z)

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D)

# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(L)

# concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
B = np.random.randn(4,4)
try:
    print(np.concatenate((A,B),axis=1))
except:
    A = np.random.randn(4,1)
    C = np.concatenate((A, B), axis = 1)

[[-0.71557654  1.45182826]
 [ 1.06682951  0.41621816]
 [ 0.73529535 -1.13360349]
 [-0.27886766  1.09607327]
 [ 1.02231708  0.33070146]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
[[-0.67670222  0.          0.          0.          0.        ]
 [-0.77838294  1.11168298  0.          0.          0.        ]
 [ 0.22101947 -1.21232794 -0.10775589  0.          0.        ]
 [-1.85946156  0.16394858  0.34929319 -1.47981723  0.        ]
 [ 2.46333894 -0.1642648   0.28700074 -1.35177253  0.72389389]]


In [4]:
print(C)

[[-0.61220209 -1.32818292 -1.12290198  1.24506923  0.43281385]
 [ 0.20584859  0.59979262  0.84133496 -0.29880344  0.1200452 ]
 [-0.70272516 -2.09760016  2.26550248 -0.84912586  0.67858226]
 [-0.46728819  0.5205528  -1.80367929  0.26402993 -0.56559287]]



---
# VIDEO: Matrix addition and subtraction
---


In [15]:

# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add them
try:
    A+B
except:
    pass
try:
    A+C
except:
    pass
# "shifting" a matrix
l = .3 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix
print(D)

[[ 4.87000394e-01 -2.33811731e+00 -1.26019032e+00  1.15061253e+00
   1.35301450e-03]
 [-2.92055347e-01 -5.65818904e-01  1.29198888e+00  7.07039289e-01
  -2.58991084e-01]
 [-3.70297265e-01 -2.95048795e-01 -4.90960492e-01 -8.45964087e-02
  -1.44221625e+00]
 [-2.34960940e-01 -1.20149626e+00  8.83596615e-01  5.82540343e-01
  -6.58679446e-02]
 [ 3.33478334e-01 -2.12268477e+00 -1.04765666e+00 -9.52698661e-01
  -3.34571236e-01]]


In [16]:
ScaledI = l*np.eye(N)
ScaledI

array([[0.3, 0. , 0. , 0. , 0. ],
       [0. , 0.3, 0. , 0. , 0. ],
       [0. , 0. , 0.3, 0. , 0. ],
       [0. , 0. , 0. , 0.3, 0. ],
       [0. , 0. , 0. , 0. , 0.3]])

In [17]:
Ds = D + ScaledI
print(Ds)

[[ 7.87000394e-01 -2.33811731e+00 -1.26019032e+00  1.15061253e+00
   1.35301450e-03]
 [-2.92055347e-01 -2.65818904e-01  1.29198888e+00  7.07039289e-01
  -2.58991084e-01]
 [-3.70297265e-01 -2.95048795e-01 -1.90960492e-01 -8.45964087e-02
  -1.44221625e+00]
 [-2.34960940e-01 -1.20149626e+00  8.83596615e-01  8.82540343e-01
  -6.58679446e-02]
 [ 3.33478334e-01 -2.12268477e+00 -1.04765666e+00 -9.52698661e-01
  -3.45712355e-02]]



---
# VIDEO: Matrix-scalar multiplication
---


In [18]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


In [26]:
m = 7
n = 5
A = np.random.randn(m,n)
B = np.random.randn(m,n)
s = np.random.random()

In [33]:
resL = s * (A + B)
resR = s*A + s*B
# Underflow, basically zero
resL - resR

array([[ 5.55111512e-17,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.11022302e-16],
       [-1.11022302e-16, -6.93889390e-18,  0.00000000e+00,
        -2.22044605e-16,  0.00000000e+00],
       [-1.38777878e-17,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.11022302e-16],
       [ 1.66533454e-16,  0.00000000e+00, -1.11022302e-16,
        -3.46944695e-18, -4.16333634e-17],
       [-5.55111512e-17,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.11022302e-16],
       [-3.46944695e-17, -1.11022302e-16, -4.44089210e-16,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.11022302e-16,
         0.00000000e+00,  0.00000000e+00]])

# VIDEO: Transpose

In [17]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T),print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]


In [24]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(np.matrix(C).H) # note the sign flips!


[[4.+1.j 3.+0.j 2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]



---
# VIDEO: Diagonal and trace
---


In [10]:

M = np.round( 5*np.random.randn(4,4) )

# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr)
print(tr2)

[  4.  10.   4.   3.]
[[  4.   0.   0.   0.]
 [  0.  10.   0.   0.]
 [  0.   0.   4.   0.]
 [  0.   0.   0.   3.]]
21.0
21.0


In [38]:
# Is trace a linear operator 

# What is the relationship between tr(A) + tr(B)

# What is the relationship between tr(l * A) + l* tr(A)
n = 4
m = 7

A = np.random.randn(m,n)
B = np.random.randn(m,n)
print(str(np.trace(A + B)) + ' should be an error')
# Should fail because needs to be square

n = m

A = np.random.randn(m,n)
B = np.random.randn(m,n)
print(np.trace(A + B))

l = np.random.randn()
print('lambda ' + str(l))

print(str(np.trace(l * A)) + ' trace of lambda *')

2.5526566866614573 should be an error
-4.677959829623364
lambda -0.34804772852370847
